---
- name: Converge
  hosts: all
  become: true

  vars:
    certbot_auto_renew_user: root

  pre_tasks:
    - name: Install cron (Debian).
      apt: name=cron state=present
      when: ansible_os_family == 'Debian'

  roles:
    - geerlingguy.certbot
